/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const ALLOWED_FUNCTIONS = [
  'ABS',
  'ALL',
  'ARRAY',
  'AVG',
  'CARDINALITY',
  'CAST',
  'CEIL',
  'CEILING',
  'CHAR',
  'CHARACTER_LENGTH',
  'CHAR_LENGTH',
  'CLASSIFIER',
  'COALESCE',
  'COLLECT',
  'CONVERT',
  'COUNT',
  'COVAR_POP',
  'COVAR_SAMP',
  'CUME_DIST',
  'CURSOR',
  'DATE',
  'DENSE_RANK',
  'DISTINCT',
  'ELEMENT',
  'EVERY',
  'EXISTS',
  'EXP',
  'EXTRACT',
  'FIRST_VALUE',
  'FLOOR',
  'FUSION',
  'GROUPING',
  'HOUR',
  'INTERSECTION',
  'INTERVAL',
  'JSON_ARRAY',
  'JSON_ARRAYAGG',
  'JSON_EXISTS',
  'JSON_OBJECT',
  'JSON_OBJECTAGG',
  'JSON_QUERY',
  'JSON_VALUE',
  'LAG',
  'LAST_VALUE',
  'LEAD',
  'LEFT',
  'LN',
  'LOCAL',
  'LOCALTIME',
  'LOCALTIMESTAMP',
  'LOWER',
  'MATCH_NUMBER',
  'MAX',
  'MIN',
  'MINUTE',
  'MOD',
  'MONTH',
  'MULTISET',
  'NEXT',
  'NOT',
  'NTH_VALUE',
  'NTILE',
  'NULLIF',
  'OCTET_LENGTH',
  'OVERLAY',
  'PERCENTILE_CONT',
  'PERCENTILE_DISC',
  'PERCENT_RANK',
  'PERIOD',
  'POSITION',
  'POWER',
  'PREV',
  'RANK',
  'REGR_COUNT',
  'REGR_SXX',
  'REGR_SYY',
  'RIGHT',
  'ROW',
  'ROW_NUMBER',
  'SECOND',
  'SOME',
  'SQRT',
  'STDDEV_POP',
  'STDDEV_SAMP',
  'STREAM',
  'SUBSTRING',
  'SUM',
  'TABLE',
  'TIME',
  'TIMESTAMP',
  'TRANSLATE',
  'TRIM',
  'TRUNCATE',
  'UNIQUE',
  'UNNEST',
  'UPPER',
  'USER',
  'VAR_POP',
  'VAR_SAMP',
  'YEAR',
];
