name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version-file: 'package.json'
          cache: 'npm'
      - run: npm install --prefer-offline --no-audit
      - name: Test
        run: npm test
      - name: Check for changes requiring a changeset
        if: github.event_name == 'pull_request'
        run: npx changeset status --since=origin/master
